# Generated by Django 6.1 on 2026-08-23 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_details', models.TextField(help_text='Provide specific proof of ownership (e.g. unique identifiers, lock screen passcode, receipt, exact contents).')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='claims_proof/')),
                ('contact_info', models.CharField(help_text='Phone number or preferred contact method', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Claim Approved'), ('REJECTED', 'Claim Rejected')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the finder/owner when reviewing this claim', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='items.item')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('item', 'claimant')},
            },
        ),
    ]
