# Generated by Django 6.1 on 2026-08-23 17:01

import django.db.models.deletion
import items.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.CharField(default='fa-box', help_text='FontAwesome icon class, e.g. fa-laptop, fa-wallet', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('item_type', models.CharField(choices=[('LOST', 'Lost Item'), ('FOUND', 'Found Item')], default='LOST', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open / Active'), ('CLAIM_PENDING', 'Claim Pending'), ('RESOLVED', 'Resolved / Returned'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('location', models.CharField(help_text='Specific place/address where item was lost or found', max_length=200)),
                ('date_lost_or_found', models.DateField(help_text='Date when the item was lost or found')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=items.models.item_directory_path)),
                ('reward', models.CharField(blank=True, help_text='Optional reward amount or note', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
