# Generated by Django 6.1.1 on 2026-09-12 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subject', models.CharField(db_index=True, help_text='User identity (username or IP address) who triggered this event', max_length=255)),
                ('action', models.CharField(choices=[('url_blocked', 'URL Blocked'), ('bola_violation', 'BOLA Violation'), ('enumeration_attempt', 'Enumeration Attempt'), ('authorization_denied', 'Authorization Denied'), ('claim_submitted', 'Claim Submitted'), ('item_created', 'Item Created'), ('item_accessed', 'Item Accessed'), ('account_login', 'Account Login'), ('password_reset', 'Password Reset'), ('security_event', 'Security Event'), ('suspicious_activity', 'Suspicious Activity')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('resource_type', models.CharField(choices=[('url', 'URL'), ('item', 'Item'), ('claim', 'Claim'), ('user', 'User'), ('endpoint', 'Endpoint'), ('resource', 'Generic Resource')], max_length=50)),
                ('resource_id', models.CharField(db_index=True, help_text='ID of the affected resource', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context (JSON): reason, client_ip, url, etc.')),
                ('source', models.CharField(db_index=True, default='manual', help_text="What system logged this (e.g., 'url_safety', 'cyberaccess', 'admin')", max_length=100)),
                ('reviewed', models.BooleanField(db_index=True, default=False, help_text='Has security team reviewed this?')),
                ('review_notes', models.TextField(blank=True, help_text='Security team review comments')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user if available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'severity'], name='audit_audit_timesta_5b18cd_idx'), models.Index(fields=['subject', 'action'], name='audit_audit_subject_4b963d_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx'), models.Index(fields=['reviewed', 'severity'], name='audit_audit_reviewe_52cad0_idx')],
            },
        ),
    ]
